---
- name: setting k8s cluster
  hosts: allservers
  become: yes
  tasks:
    - name: stop firewalld
      service:
        name: firewalld
        state: stopped
        enabled: no

    - name: set SELinux to permissive
      command: setenforce 0

    - name: set SELinux to permissive permanently
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=permissive'
        backrefs: yes

    - name: swap off
      command: swapoff -a

    - name: swap off permanently
      lineinfile:
        path: /etc/fstab
        regexp: '^\/dev\/mapper\/rl-swap'
        line: '#\/dev\/mapper\/rl-swap     none                    swap    defaults        0 0'
        backrefs: yes

    - name: daemon-reload
      systemd:
        daemon_reload: yes

    - name: Create sysctl config file
      copy:
        dest: /etc/sysctl.d/k8s-mod.conf
        content: |
          net.bridge.bridge-nf-call-iptables=1
          net.ipv4.ip_forward=1
          net.bridge.bridge-nf-call-ip6tables=1
        owner: root
        group: root
        mode: '0644'

    - name: apply sysctl config
      command: sysctl --system -q

    - name: Create module config file
      copy:
        dest: /etc/modules-load.d/k8s-modules.conf
        content: |
          br_netfilter
          overlay
        owner: root
        group: root
        mode: '0644'

    - name: apply br_netfilter
      command: modprobe br_netfilter
    - name: apply overlay
      command: modprobe overlay

    - name: configure hosts file
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        create: yes
      loop:
        - "192.168.0.10 node1.example.com node1"
        - "192.168.0.20 node2.example.com node2"
        - "192.168.0.30 node3.example.com node3"

